"""
Public fire-weather zone alert map.

Mirrors routers/burn_bans.py's active/active.geojson pair: the static PNG
(colored by NWS Red Flag Warning / Fire Weather Watch status per fire
weather zone) and the matching zone-level GeoJSON, both regenerated by the
5-minute alert poll in alerts/activemoalerts.py.
"""
from fastapi import APIRouter, Response

from services.mobile_content import active_fire_weather_alerts

router = APIRouter()


@router.get("/api/fire-weather-alerts/active")
def list_active_fire_weather_alerts(response: Response):
    response.headers["Cache-Control"] = "public, max-age=300"
    from services.fire_weather_alert_map import ensure_fire_weather_alert_map
    alerts = active_fire_weather_alerts()
    return {
        "success": True,
        "count": len(alerts),
        "alerts": alerts,
        "map": ensure_fire_weather_alert_map(),
    }


@router.get("/api/fire-weather-alerts/active.geojson")
def list_active_fire_weather_alerts_geojson(response: Response):
    response.headers["Cache-Control"] = "public, max-age=300"
    from services.fire_weather_alert_map import fire_weather_alert_feature_collection
    return fire_weather_alert_feature_collection()
